### ISSUE TITLE
Bug: DC component is wrong

### ISSUE THREAD

**Issue by KronosTheLate** [KronosTheLate/EasyFFTs.jl#11]
See the following example:
```julia
julia> using EasyFFTs, FFTW

julia> let sig = ones(10000)
           easyfft(sig) |> display
           getindex(fft(sig)./length(sig), 1) |> display
       end
EasyFFT with 5001 samples.
Dominant component(s):              ╷              
   Frequency  │  Magnitude   
╺━━━━━━━━━━━━━┿━━━━━━━━━━━━━╸
      0.0     │   1.9996     
              ╵              

1.0 + 0.0im
```

The easyfft version estimates the DC amplitude to be double of what it actually is.

**Comment by KronosTheLate** [comment]
Is it appropriate to simply divide DC component by 2? This really makes it an improper version of `rfft`, but the entire point is that the native synthesis formula of multiplying sinusoids of the amplitudes and frequencies should work, which requires this.

**Comment by KronosTheLate** [comment]
This is not really acceptable:
```julia
julia> let sig = ones(10000)
           @show easyfft(sig)
           @show easyfft(sig.|>ComplexF64)
       end
easyfft(sig) = EasyFFT with 5001 samples.
Dominant component(s):              ╷              
   Frequency  │  Magnitude   
╺━━━━━━━━━━━━━┿━━━━━━━━━━━━━╸
      0.0     │   1.9996     
              ╵              

easyfft(sig .|> ComplexF64) = EasyFFT with 10000 samples.
Dominant component(s):              ╷              
   Frequency  │  Magnitude   
╺━━━━━━━━━━━━━┿━━━━━━━━━━━━━╸
      0.0     │     1.0      
              ╵              

EasyFFT with 10000 samples.
Dominant component(s):              ╷              
   Frequency  │  Magnitude   
╺━━━━━━━━━━━━━┿━━━━━━━━━━━━━╸
      0.0     │     1.0      
              ╵              

```

I will divide the DC component in the AbstractVector{<: Real} method.

**Comment by gustaphe** [comment]
I don't quite remember the theory, but this seems necessary. I also remember having done something like this manually in the past so it's probably right. I think `rfft` includes the DC component twice (f = ±0). Can't really speak for whether that's correct, but the useful thing is to halve it.

**Comment by KronosTheLate** [comment]
Agreed. I will keep the halving implemented in the last PR. I am also implementing a new function that I needed, so I will tag a new release once that is added.

**Comment by KronosTheLate** [comment]
I implemented the mentioned function in https://github.com/KronosTheLate/EasyFFTs.jl/commit/f1c382b6e5afee83b996cc4aa937f1e11811a246, along with fixing typos, moving utility functions into "utils.jl", make `domfreqs` use `finddomfreqs` internally, and updating the readme. We also need some tests at this point, just because I always have an uncertainty about if I accidentally broke something. If you have the time and energy, a review of the changes would be appreciated.
