### ISSUE TITLE
Disallow indexing EasyFFT

### ISSUE THREAD

**Issue by KronosTheLate** [KronosTheLate/EasyFFTs.jl#6]
When an object of type EasyFFT is indexed, it corresponds to indexing the response.
When iterating it, the frequency vector and response vector are returned. I find that quite unintuitive, as the behaviour seems conflicting. 

I am therefore in favor of disallowing indexing EasyFFT instances directly, or returning the vectors themselves (corresponding with what is returned for iteration).
Pinging @gustaphe as the implementer of the discussed issue.

**Comment by gustaphe** [comment]
I made it that way to keep the previous behavior when assigning to a tuple, but I don't think it's super important. Feel free to break it :)
