### ISSUE TITLE
Make `Phase` return degrees instead of radians

### ISSUE THREAD

**Issue by KronosTheLate** [KronosTheLate/EasyFFTs.jl#7]
It is generally harder to interpret radians than degrees. This has to do with the irrational and fractional values defined to understand them. Personally I would prefer to normalize the phase to 2pi, as it corresponds to complete revolutions, but degrees is more common. I therefore think it would be more convenient to most.

**Comment by gustaphe** [comment]
Strong disagree. Note how most angular operations in Julia assume radians by default: `sin` vs `sind`, `cos` vs `cosd` ...

Consider adding a `phased` command instead.

**Comment by KronosTheLate** [comment]
Haha not sure if you wrote this before or after, but I did exactly this yesterday. Thanks for the input though!
